name: cdk release code

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
      CDK_APP_NAME:
        required: true
        type: string
      LOG_RETENTION_IN_DAYS:
        required: true
        type: string
      useMockOidc:
        type: boolean
        default: false
      primaryOidcIssuer:
        type: string
      primaryOidcAuthorizeEndpoint:
        type: string
      primaryOidcTokenEndpoint:
        type: string
      primaryOidcUserInfoEndpoint:
        type: string
      primaryOidcjwksEndpoint:
        type: string
      mockOidcIssuer:
        type: string
      mockOidcAuthorizeEndpoint:
        type: string
      mockOidcTokenEndpoint:
        type: string
      mockOidcUserInfoEndpoint:
        type: string
      mockOidcjwksEndpoint:
        type: string
      useLocalhostCallback:
        type: boolean
      useCustomCognitoDomain:
        type: boolean
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
      CDK_PULL_IMAGE_ROLE:
        required: true
      primaryOidcClientId:
        required: false
      primaryOidClientSecret:
        required: false
      mockOidcClientId:
        required: false
      mockOidClientSecret:
        required: false
jobs:
  release_code:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    name: deploy cdk app ${{ inputs.CDK_APP_NAME }}
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout local github actions
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
          sparse-checkout: |
            .github

      - name: Configure AWS Credentials
        id: connect-aws-pull-image
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CDK_PULL_IMAGE_ROLE }}
          role-session-name: prescription-clinical-tracker-ui-pull-image

      - name: build_artifact download
        uses: actions/download-artifact@v4
        with:
          name: build_artifact

      - name: extract build_artifact
        run: |
          mkdir -p .build
          tar -xf artifact.tar -C .build

      - name: Retrieve AWS Account ID
        id: retrieve-account-id
        run: echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> "$GITHUB_ENV"

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com

      - name: Pull cdk-utils-build from Amazon ECR
        run: |
          docker pull "${{ env.ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/cdk-utils-build-repo:latest"
          docker tag "${{ env.ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/cdk-utils-build-repo:latest" cdk-utils-build-repo:latest

      - name: Configure AWS Credentials
        id: connect-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: prescription-clinical-tracker-ui-deployment
          output-credentials: true
  
      - name: fix cdk.json for deployment
        run: |
          # shellcheck disable=SC2140
          epsDomainName=$(aws cloudformation list-exports --region eu-west-2 --query "Exports[?Name=='"eps-route53-resources:EPS-domain"'].Value" --output text)
          # shellcheck disable=SC2140
          epsHostedZoneId=$(aws cloudformation list-exports --region eu-west-2 --query "Exports[?Name=='"eps-route53-resources:EPS-ZoneID"'].Value" --output text)
          # shellcheck disable=SC2140
          cloudfrontDistributionId=$(aws cloudformation list-exports --region eu-west-2 --query "Exports[?Name=='"${{ inputs.SERVICE_NAME }}-stateless-resources:cloudfrontDistribution:Id"'].Value" --output text)
          # shellcheck disable=SC2140
          cloudfrontCertArn=$(aws cloudformation list-exports --region us-east-1 --query "Exports[?Name=='"${{ inputs.SERVICE_NAME }}-us-certs:cloudfrontCertificate:Arn"'].Value" --output text)
          # shellcheck disable=SC2140
          shortCloudfrontDomain=$(aws cloudformation list-exports --region us-east-1 --query "Exports[?Name=='"${{ inputs.SERVICE_NAME }}-us-certs:shortCloudfrontDomain:Name"'].Value" --output text)
          # shellcheck disable=SC2140
          fullCloudfrontDomain=$(aws cloudformation list-exports --region us-east-1 --query "Exports[?Name=='"${{ inputs.SERVICE_NAME }}-us-certs:fullCloudfrontDomain:Name"'].Value" --output text)
          jq \
          --arg serviceName "${{ inputs.SERVICE_NAME }}" \
          --arg VERSION_NUMBER "${{ inputs.VERSION_NUMBER }}" \
          --arg COMMIT_ID "${{ inputs.COMMIT_ID }}" \
          --arg logRetentionInDays "${{ inputs.LOG_RETENTION_IN_DAYS }}" \
          --arg epsDomainName "${epsDomainName}" \
          --arg epsHostedZoneId "${epsHostedZoneId}" \
          --argjson allowAutoDeleteObjects "true" \
          --arg cloudfrontDistributionId "${cloudfrontDistributionId}" \
          --arg cloudfrontCertArn "${cloudfrontCertArn}" \
          --arg useMockOidc "${{ inputs.useMockOidc }}" \
          --arg primaryOidcClientId "${{ secrets.primaryOidcClientId }}" \
          --arg primaryOidClientSecret "${{ secrets.primaryOidClientSecret }}" \
          --arg primaryOidcIssuer "${{ inputs.primaryOidcIssuer }}" \
          --arg primaryOidcAuthorizeEndpoint "${{ inputs.primaryOidcAuthorizeEndpoint }}" \
          --arg primaryOidcTokenEndpoint "${{ inputs.primaryOidcTokenEndpoint }}" \
          --arg primaryOidcUserInfoEndpoint "${{ inputs.primaryOidcUserInfoEndpoint }}" \
          --arg primaryOidcjwksEndpoint "${{ inputs.primaryOidcjwksEndpoint }}" \
          --arg mockOidcClientId "${{ secrets.mockOidcClientId }}" \
          --arg mockOidClientSecret "${{ secrets.mockOidClientSecret }}" \
          --arg mockOidcIssuer "${{ inputs.mockOidcIssuer }}" \
          --arg mockOidcAuthorizeEndpoint "${{ inputs.mockOidcAuthorizeEndpoint }}" \
          --arg mockOidcTokenEndpoint "${{ inputs.mockOidcTokenEndpoint }}" \
          --arg mockOidcUserInfoEndpoint "${{ inputs.mockOidcUserInfoEndpoint }}" \
          --arg mockOidcjwksEndpoint "${{ inputs.mockOidcjwksEndpoint }}" \
          --arg shortCloudfrontDomain "${shortCloudfrontDomain}" \
          --arg fullCloudfrontDomain "${fullCloudfrontDomain}" \
          --argjson useCustomCognitoDomain "${{ inputs.useCustomCognitoDomain }}" \
          --argjson useLocalhostCallback "${{ inputs.useLocalhostCallback }}" \
          '.context += {
            "serviceName": $serviceName,
            "VERSION_NUMBER": $VERSION_NUMBER,
            "COMMIT_ID": $COMMIT_ID,
            "logRetentionInDays": $logRetentionInDays,
            "epsDomainName": $epsDomainName,
            "epsHostedZoneId": $epsHostedZoneId,
            "allowAutoDeleteObjects": $allowAutoDeleteObjects,
            "cloudfrontDistributionId": $cloudfrontDistributionId,
            "cloudfrontCertArn": $cloudfrontCertArn,
            "shortCloudfrontDomain": $shortCloudfrontDomain,
            "fullCloudfrontDomain": $fullCloudfrontDomain,
            "useMockOidc": $useMockOidc,
            "primaryOidcClientId": $primaryOidcClientId,
            "primaryOidClientSecret": $primaryOidClientSecret,
            "primaryOidcIssuer": $primaryOidcIssuer,
            "primaryOidcAuthorizeEndpoint": $primaryOidcAuthorizeEndpoint,
            "primaryOidcTokenEndpoint": $primaryOidcTokenEndpoint,
            "primaryOidcUserInfoEndpoint": $primaryOidcUserInfoEndpoint,
            "primaryOidcjwksEndpoint": $primaryOidcjwksEndpoint,
            "mockOidcClientId": $mockOidcClientId,
            "mockOidClientSecret": $mockOidClientSecret,
            "mockOidcIssuer": $mockOidcIssuer,
            "mockOidcAuthorizeEndpoint": $mockOidcAuthorizeEndpoint,
            "mockOidcTokenEndpoint": $mockOidcTokenEndpoint,
            "mockOidcUserInfoEndpoint": $mockOidcUserInfoEndpoint,
            "mockOidcjwksEndpoint": $mockOidcjwksEndpoint,
            "useCustomCognitoDomain": $useCustomCognitoDomain,
            "useLocalhostCallback": $useLocalhostCallback}' \
          .build/cdk.json > .build/cdk.new.json
          mv .build/cdk.new.json .build/cdk.json

      - name: Show diff
        run: |
          docker run \
          -v "$(pwd)/.build":/home/cdkuser/workspace/ \
          -e AWS_ACCESS_KEY_ID=${{ steps.connect-aws.outputs.aws-access-key-id }} \
          -e AWS_SECRET_ACCESS_KEY=${{ steps.connect-aws.outputs.aws-secret-access-key }} \
          -e AWS_SESSION_TOKEN=${{ steps.connect-aws.outputs.aws-session-token }} \
          -e AWS_REGION="eu-west-2" \
          -e SHOW_DIFF="true" \
          -e DEPLOY_CODE="false" \
          -e CDK_APP_PATH="packages/cdk/bin/${{ inputs.CDK_APP_NAME }}.ts" \
          cdk-utils-build-repo:latest
        shell: bash

      - name: Deploy code
        run: |
          docker run \
          -v "$(pwd)/.build":/home/cdkuser/workspace/ \
          -e AWS_ACCESS_KEY_ID=${{ steps.connect-aws.outputs.aws-access-key-id }} \
          -e AWS_SECRET_ACCESS_KEY=${{ steps.connect-aws.outputs.aws-secret-access-key }} \
          -e AWS_SESSION_TOKEN=${{ steps.connect-aws.outputs.aws-session-token }} \
          -e AWS_REGION="eu-west-2" \
          -e SHOW_DIFF="false" \
          -e DEPLOY_CODE="true" \
          -e CDK_APP_PATH="packages/cdk/bin/${{ inputs.CDK_APP_NAME }}.ts" \
          cdk-utils-build-repo:latest
        shell: bash
